/**
 * The page list. Every audit imports this so a new page is only ever added in
 * one place.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { WORKS } from './works-data.mjs';

export const HAND_WRITTEN = [
  'index', 'da', 'now', 'works', 'series', 'catalogue',
  'series-like-a-flower', 'series-gigantically-subtle', 'series-hour-of-gold',
  'exhibitions', 'visit', 'i-see-you', 'kvindecirkel', 'journal', 'prints', 'sessions',
  'press', 'about', 'contact', 'colophon', '404',
];

/** Generated by tools/build-work-pages.mjs — audited alongside everything else. */
export const WORK_PAGES = WORKS.map((work) => `work-${work.slug}`);

/** Pages worth re-checking under the expensive per-mode passes. */
export const SAMPLE = ['index', 'works', 'contact', 'prints', 'now', 'da', 'work-untitled-poppy-i'];

export const PAGES = [...HAND_WRITTEN, ...WORK_PAGES];

/**
 * Find a usable Chromium in the Playwright cache. This used to be a hardcoded
 * path to build 1228; installing another browser replaced it with 1234 and every
 * audit broke. Resolve the newest build present instead.
 */
export function chromiumPath() {
  const cache = path.join(os.homedir(), 'Library', 'Caches', 'ms-playwright');
  if (!fs.existsSync(cache)) throw new Error('No Playwright browser cache — run: npx playwright install chromium');
  const builds = fs.readdirSync(cache)
    .filter((name) => /^chromium-\d+$/.test(name))
    .sort((a, b) => Number(b.split('-')[1]) - Number(a.split('-')[1]));
  for (const build of builds) {
    for (const candidate of [
      'chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',
      'chrome-mac/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',
      'chrome-linux/chrome',
    ]) {
      const executable = path.join(cache, build, candidate);
      if (fs.existsSync(executable)) return executable;
    }
  }
  throw new Error('No Chromium found — run: npx playwright install chromium');
}

/**
 * Resolve a browser engine.
 *
 * Chromium comes from patchright, which is what the audits have always used.
 * WebKit is only reachable through the stock playwright-core installed beside it
 * — patchright pins an older WebKit build than the one on disk — so it is looked
 * up separately and reported clearly when missing.
 */
export async function launcher(engine = 'chromium') {
  if (engine === 'chromium') {
    const { chromium } = await import('/Users/mga/.npm/_npx/945f35517ce0271a/node_modules/@playwriter/patchright-core/index.mjs');
    return { browserType: chromium, launchOptions: { executablePath: chromiumPath() } };
  }
  if (engine === 'webkit') {
    const module = await import(playwrightCore());
    const webkit = module.webkit || (module.default && module.default.webkit);
    if (!webkit) throw new Error('WebKit not available — run: npx playwright install webkit');
    return { browserType: webkit, launchOptions: {} };
  }
  throw new Error(`Unknown engine "${engine}" — use chromium or webkit`);
}

/** Locate a playwright-core that can drive the installed WebKit. */
function playwrightCore() {
  const npx = path.join(os.homedir(), '.npm', '_npx');
  const installed = fs.readdirSync(path.join(os.homedir(), 'Library', 'Caches', 'ms-playwright'))
    .filter((name) => name.startsWith('webkit-'))
    .map((name) => Number(name.split('-')[1]));
  for (const directory of fs.readdirSync(npx)) {
    const core = path.join(npx, directory, 'node_modules', 'playwright-core');
    const registry = path.join(core, 'browsers.json');
    if (!fs.existsSync(registry)) continue;
    const wanted = JSON.parse(fs.readFileSync(registry, 'utf8')).browsers.find((entry) => entry.name === 'webkit');
    if (wanted && installed.includes(Number(wanted.revision))) return path.join(core, 'index.js');
  }
  throw new Error('No playwright-core matches the installed WebKit — run: npx playwright install webkit');
}
