/**
 * The page list, in nav order. Every audit imports this so a new page is only
 * ever added in one place.
 */
export const HAND_WRITTEN = [
  'index',
  'da',
  'now',
  'works',
  'series',
  'series-like-a-flower',
  'series-gigantically-subtle',
  'series-hour-of-gold',
  'exhibitions',
  'i-see-you',
  'kvindecirkel',
  'journal',
  'prints',
  'sessions',
  'press',
  'about',
  'contact',
  'search',
  'colophon',
  '404',
];

/** Generated by tools/build-work-pages.mjs — audited alongside everything else. */
export const WORK_PAGES = [
  'work-untitled-poppy-i',
  'work-untitled-clematis',
  'work-afternoon-wall',
  'work-koge-bugt-2140',
  'work-self-facing-up',
  'work-green-hour',
  'work-dusk-crossing',
  'work-seed-head-waiting',
  'work-gigantically-subtle-no-4',
  'work-greve-strand-facing-south',
  'work-second-opening',
  'work-i-see-you-study',
];

/** Pages worth re-checking under the expensive per-mode passes. */
export const SAMPLE = ['index', 'works', 'contact', 'prints', 'now', 'da', 'work-untitled-poppy-i'];

export const PAGES = [...HAND_WRITTEN, ...WORK_PAGES];

export const CHROMIUM =
  process.env.HOME +
  '/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing';
